# Generated by Django 5.1.4 on 2026-01-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='jira_issue_key',
            field=models.CharField(blank=True, help_text='Jira issue key if synced to Jira', max_length=50, null=True),
        ),
    ]
