# Generated by Django 5.1.4 on 2026-01-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_jira_issue_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='jira_issue_id',
            field=models.CharField(blank=True, help_text='Jira issue ID if synced to Jira', max_length=50, null=True),
        ),
    ]
