# Generated by Django 5.1.4 on 2026-01-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticket_jira_issue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='jira_comment_id',
            field=models.CharField(blank=True, help_text='Jira comment ID if synced to Jira', max_length=50, null=True),
        ),
    ]
